# Android ??????
# ?????? key.properties ??????????

# ?????
storePassword=beyoit123456!@#

# ????
keyPassword=spdbank123456!@#

# ????
keyAlias=spdbank

# ?????????? app ???
storeFile=beyoit-spdbank.jks

